# Generated by Django 5.0.6 on 2024-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Введите имя', max_length=64, unique=True, verbose_name='Имя первого гостя')),
                ('fullname2', models.CharField(blank=True, help_text='Введите имя', max_length=64, null=True, unique=True, verbose_name='Имя второго гостя')),
                ('fullname3', models.CharField(blank=True, help_text='Введите имя', max_length=64, null=True, unique=True, verbose_name='Имя третьего гостя')),
                ('is_confirm_yes', models.BooleanField(default=False, verbose_name='Приду')),
                ('is_confirm_no', models.BooleanField(default=False, verbose_name='Не приду')),
                ('is_confirm_together', models.BooleanField(default=False, verbose_name='Приду не один')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Гости',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название музыки', max_length=64, unique=True, verbose_name='Музыка')),
                ('image', models.FileField(blank=True, help_text='Загрузите музыку', null=True, upload_to='music/', verbose_name='Музыка')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыка',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название фото', max_length=64, unique=True, verbose_name='Название Фото')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0, help_text='Введите количество дней', verbose_name='День')),
                ('hours', models.IntegerField(default=0, help_text='Введите количество часов', verbose_name='Час')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.DeleteModel(
            name='GuestResponse',
        ),
    ]
