# Generated by Django 5.0.6 on 2024-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_guest_music_photo_time_delete_guestresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='text',
            field=models.TextField(default='', help_text='Введите текст пожелания', verbose_name='Пожелания молодоженам'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='fullname',
            field=models.CharField(default='', help_text='Введите имя', max_length=128, unique=True, verbose_name='Имя первого гостя'),
        ),
    ]
