# Generated by Django 5.0.6 on 2024-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_guest_text_alter_guest_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='fullname',
            field=models.CharField(default='', help_text='Введите имя', max_length=128, verbose_name='Имя первого гостя'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fullname2',
            field=models.CharField(blank=True, help_text='Введите имя', max_length=64, null=True, verbose_name='Имя второго гостя'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fullname3',
            field=models.CharField(blank=True, help_text='Введите имя', max_length=64, null=True, verbose_name='Имя третьего гостя'),
        ),
    ]
